

VENDOR_NAME : 'TSGENVIRO'
PRODUCT_CODE : 'TSG-1'
VENDOR_URL : 'https://www.tsgchile.cl/'
PRODUCT_NAME : 'TSG-ENV-MB-Server'
MODEL_NAME : 'TSG-ENV-MB-Server'
MAJOR_MINOR_REV : '1.0.0'

SERVER_PORT: 5020
